# Generated by Django 5.0.4 on 2024-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiondetection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image',
            field=models.ImageField(null=True, upload_to='emotions'),
        ),
    ]
