# Generated by Django 5.0.4 on 2024-05-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiondetection', '0004_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='image',
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='emotions')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('registeredUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotiondetection.registereduser')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='detected_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detect_emotions', to='emotiondetection.uploadedimage'),
        ),
    ]
