# Generated by Django 5.0.4 on 2024-06-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiondetection', '0005_remove_analysisresult_image_uploadedimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='registeredUser',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
