# Generated by Django 5.0.4 on 2024-05-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotiondetection', '0003_alter_analysisresult_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
